name: Fuzz
on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  fuzz:
    uses: paulmillr/cryptofuzz/.github/workflows/noble-commit-fuzz.yml@c4c2c6054b3545f7d6bb0f8608371a6a6f3c93fb
    with:
      ref: ${{ github.sha }}