name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: jsbt v0.6.5
    uses: paulmillr/jsbt/.github/workflows/release.yml@5320e209ca8cc9b1b0b569675e164bdd2a139d71
    permissions:
      contents: read
      id-token: write
