name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: jsbt v0.7.1
    uses: paulmillr/jsbt/.github/workflows/release.yml@c138efca67d90dce86a7cc22c01d6b66d193ea7a
    permissions:
      contents: read
      id-token: write
