name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: jsbt v0.5.2
    uses: paulmillr/jsbt/.github/workflows/release.yml@3b6bf563e416e9c6047db19410988922084e1e92
    permissions:
      contents: read
      id-token: write
