name: Run TS tests
on:
  - push
  - pull_request
jobs:
  test-ts:
    name: 'jsbt v0.4.2' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-ts.yml@5194a28c9f94ad504090fe037fe6efb41e5b8964
